#!/bin/sh
set -eu
RUNTIME_ROOT=${C2PASEQ_AUDFPRINT_RUNTIME:-"${HOME}/Library/Application Support/C2PA Creative Sequencer/Fingerprint"}
exec "${RUNTIME_ROOT}/venv/bin/python" "${RUNTIME_ROOT}/lib/audfprint_helper.py" \
    --source "${RUNTIME_ROOT}/source/audfprint" \
    --commit "cb03ba99feafd41b8874307f0f4e808a6ce34362" "$@"
